version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./app:/var/www/html  # Aplicação Laravel
      - ./.docker/nginx:/etc/nginx/conf.d  # Configurações do Nginx
      - ./logs/nginx:/var/log/nginx  # Logs do Nginx
    container_name: azapfy-nginx

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./app:/var/www/html
      - ./.docker/php:/usr/local/etc/php/conf.d  # Configurações do PHP
      - ./logs/php.log:/var/log/fpm-php.www.log  # Logs do PHP-FPM
    container_name: azapfy-php
    expose:
      - "9000"

  mysql:
    container_name: azapfy-db
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'dev-user'
      MYSQL_PASS: 'dev-password'
    volumes:
      - ./mysql/db-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge